/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TandaTanganRouteImport } from './routes/tanda-tangan'
import { Route as SopRouteImport } from './routes/sop'
import { Route as ProsesBisnisRouteImport } from './routes/proses-bisnis'
import { Route as PersetujuanRouteImport } from './routes/persetujuan'
import { Route as PeraturanRouteImport } from './routes/peraturan'
import { Route as PemeriksaanRouteImport } from './routes/pemeriksaan'
import { Route as PelaksanaRouteImport } from './routes/pelaksana'
import { Route as MeRouteImport } from './routes/me'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TandaTanganIndexRouteImport } from './routes/tanda-tangan.index'
import { Route as SopIndexRouteImport } from './routes/sop.index'
import { Route as ProsesBisnisIndexRouteImport } from './routes/proses-bisnis.index'
import { Route as PersetujuanIndexRouteImport } from './routes/persetujuan.index'
import { Route as PeraturanIndexRouteImport } from './routes/peraturan.index'
import { Route as PemeriksaanIndexRouteImport } from './routes/pemeriksaan.index'
import { Route as PelaksanaIndexRouteImport } from './routes/pelaksana.index'
import { Route as MeIndexRouteImport } from './routes/me.index'
import { Route as LoginIndexRouteImport } from './routes/login.index'
import { Route as ArsipIndexRouteImport } from './routes/arsip.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as SopIdRouteImport } from './routes/sop.$id'
import { Route as AdminProsesBisnisOrganisasiRouteImport } from './routes/admin.proses-bisnis-organisasi'
import { Route as AdminKewenanganOrganisasiRouteImport } from './routes/admin.kewenangan-organisasi'
import { Route as AdminAkunFtiRouteImport } from './routes/admin.akun-fti'
import { Route as ValidasiPdfIndexRouteImport } from './routes/validasi.pdf.index'
import { Route as ValidasiPengesahanDokumenTteIdUserIdRouteImport } from './routes/validasi.pengesahan.$dokumenTteId.$userId'

const TandaTanganRoute = TandaTanganRouteImport.update({
  id: '/tanda-tangan',
  path: '/tanda-tangan',
  getParentRoute: () => rootRouteImport,
} as any)
const SopRoute = SopRouteImport.update({
  id: '/sop',
  path: '/sop',
  getParentRoute: () => rootRouteImport,
} as any)
const ProsesBisnisRoute = ProsesBisnisRouteImport.update({
  id: '/proses-bisnis',
  path: '/proses-bisnis',
  getParentRoute: () => rootRouteImport,
} as any)
const PersetujuanRoute = PersetujuanRouteImport.update({
  id: '/persetujuan',
  path: '/persetujuan',
  getParentRoute: () => rootRouteImport,
} as any)
const PeraturanRoute = PeraturanRouteImport.update({
  id: '/peraturan',
  path: '/peraturan',
  getParentRoute: () => rootRouteImport,
} as any)
const PemeriksaanRoute = PemeriksaanRouteImport.update({
  id: '/pemeriksaan',
  path: '/pemeriksaan',
  getParentRoute: () => rootRouteImport,
} as any)
const PelaksanaRoute = PelaksanaRouteImport.update({
  id: '/pelaksana',
  path: '/pelaksana',
  getParentRoute: () => rootRouteImport,
} as any)
const MeRoute = MeRouteImport.update({
  id: '/me',
  path: '/me',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TandaTanganIndexRoute = TandaTanganIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TandaTanganRoute,
} as any)
const SopIndexRoute = SopIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SopRoute,
} as any)
const ProsesBisnisIndexRoute = ProsesBisnisIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProsesBisnisRoute,
} as any)
const PersetujuanIndexRoute = PersetujuanIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PersetujuanRoute,
} as any)
const PeraturanIndexRoute = PeraturanIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PeraturanRoute,
} as any)
const PemeriksaanIndexRoute = PemeriksaanIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PemeriksaanRoute,
} as any)
const PelaksanaIndexRoute = PelaksanaIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PelaksanaRoute,
} as any)
const MeIndexRoute = MeIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MeRoute,
} as any)
const LoginIndexRoute = LoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArsipIndexRoute = ArsipIndexRouteImport.update({
  id: '/arsip/',
  path: '/arsip/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const SopIdRoute = SopIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => SopRoute,
} as any)
const AdminProsesBisnisOrganisasiRoute =
  AdminProsesBisnisOrganisasiRouteImport.update({
    id: '/proses-bisnis-organisasi',
    path: '/proses-bisnis-organisasi',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminKewenanganOrganisasiRoute =
  AdminKewenanganOrganisasiRouteImport.update({
    id: '/kewenangan-organisasi',
    path: '/kewenangan-organisasi',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminAkunFtiRoute = AdminAkunFtiRouteImport.update({
  id: '/akun-fti',
  path: '/akun-fti',
  getParentRoute: () => AdminRoute,
} as any)
const ValidasiPdfIndexRoute = ValidasiPdfIndexRouteImport.update({
  id: '/validasi/pdf/',
  path: '/validasi/pdf/',
  getParentRoute: () => rootRouteImport,
} as any)
const ValidasiPengesahanDokumenTteIdUserIdRoute =
  ValidasiPengesahanDokumenTteIdUserIdRouteImport.update({
    id: '/validasi/pengesahan/$dokumenTteId/$userId',
    path: '/validasi/pengesahan/$dokumenTteId/$userId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/me': typeof MeRouteWithChildren
  '/pelaksana': typeof PelaksanaRouteWithChildren
  '/pemeriksaan': typeof PemeriksaanRouteWithChildren
  '/peraturan': typeof PeraturanRouteWithChildren
  '/persetujuan': typeof PersetujuanRouteWithChildren
  '/proses-bisnis': typeof ProsesBisnisRouteWithChildren
  '/sop': typeof SopRouteWithChildren
  '/tanda-tangan': typeof TandaTanganRouteWithChildren
  '/admin/akun-fti': typeof AdminAkunFtiRoute
  '/admin/kewenangan-organisasi': typeof AdminKewenanganOrganisasiRoute
  '/admin/proses-bisnis-organisasi': typeof AdminProsesBisnisOrganisasiRoute
  '/sop/$id': typeof SopIdRoute
  '/admin/': typeof AdminIndexRoute
  '/arsip/': typeof ArsipIndexRoute
  '/login/': typeof LoginIndexRoute
  '/me/': typeof MeIndexRoute
  '/pelaksana/': typeof PelaksanaIndexRoute
  '/pemeriksaan/': typeof PemeriksaanIndexRoute
  '/peraturan/': typeof PeraturanIndexRoute
  '/persetujuan/': typeof PersetujuanIndexRoute
  '/proses-bisnis/': typeof ProsesBisnisIndexRoute
  '/sop/': typeof SopIndexRoute
  '/tanda-tangan/': typeof TandaTanganIndexRoute
  '/validasi/pdf/': typeof ValidasiPdfIndexRoute
  '/validasi/pengesahan/$dokumenTteId/$userId': typeof ValidasiPengesahanDokumenTteIdUserIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin/akun-fti': typeof AdminAkunFtiRoute
  '/admin/kewenangan-organisasi': typeof AdminKewenanganOrganisasiRoute
  '/admin/proses-bisnis-organisasi': typeof AdminProsesBisnisOrganisasiRoute
  '/sop/$id': typeof SopIdRoute
  '/admin': typeof AdminIndexRoute
  '/arsip': typeof ArsipIndexRoute
  '/login': typeof LoginIndexRoute
  '/me': typeof MeIndexRoute
  '/pelaksana': typeof PelaksanaIndexRoute
  '/pemeriksaan': typeof PemeriksaanIndexRoute
  '/peraturan': typeof PeraturanIndexRoute
  '/persetujuan': typeof PersetujuanIndexRoute
  '/proses-bisnis': typeof ProsesBisnisIndexRoute
  '/sop': typeof SopIndexRoute
  '/tanda-tangan': typeof TandaTanganIndexRoute
  '/validasi/pdf': typeof ValidasiPdfIndexRoute
  '/validasi/pengesahan/$dokumenTteId/$userId': typeof ValidasiPengesahanDokumenTteIdUserIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/me': typeof MeRouteWithChildren
  '/pelaksana': typeof PelaksanaRouteWithChildren
  '/pemeriksaan': typeof PemeriksaanRouteWithChildren
  '/peraturan': typeof PeraturanRouteWithChildren
  '/persetujuan': typeof PersetujuanRouteWithChildren
  '/proses-bisnis': typeof ProsesBisnisRouteWithChildren
  '/sop': typeof SopRouteWithChildren
  '/tanda-tangan': typeof TandaTanganRouteWithChildren
  '/admin/akun-fti': typeof AdminAkunFtiRoute
  '/admin/kewenangan-organisasi': typeof AdminKewenanganOrganisasiRoute
  '/admin/proses-bisnis-organisasi': typeof AdminProsesBisnisOrganisasiRoute
  '/sop/$id': typeof SopIdRoute
  '/admin/': typeof AdminIndexRoute
  '/arsip/': typeof ArsipIndexRoute
  '/login/': typeof LoginIndexRoute
  '/me/': typeof MeIndexRoute
  '/pelaksana/': typeof PelaksanaIndexRoute
  '/pemeriksaan/': typeof PemeriksaanIndexRoute
  '/peraturan/': typeof PeraturanIndexRoute
  '/persetujuan/': typeof PersetujuanIndexRoute
  '/proses-bisnis/': typeof ProsesBisnisIndexRoute
  '/sop/': typeof SopIndexRoute
  '/tanda-tangan/': typeof TandaTanganIndexRoute
  '/validasi/pdf/': typeof ValidasiPdfIndexRoute
  '/validasi/pengesahan/$dokumenTteId/$userId': typeof ValidasiPengesahanDokumenTteIdUserIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/me'
    | '/pelaksana'
    | '/pemeriksaan'
    | '/peraturan'
    | '/persetujuan'
    | '/proses-bisnis'
    | '/sop'
    | '/tanda-tangan'
    | '/admin/akun-fti'
    | '/admin/kewenangan-organisasi'
    | '/admin/proses-bisnis-organisasi'
    | '/sop/$id'
    | '/admin/'
    | '/arsip/'
    | '/login/'
    | '/me/'
    | '/pelaksana/'
    | '/pemeriksaan/'
    | '/peraturan/'
    | '/persetujuan/'
    | '/proses-bisnis/'
    | '/sop/'
    | '/tanda-tangan/'
    | '/validasi/pdf/'
    | '/validasi/pengesahan/$dokumenTteId/$userId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin/akun-fti'
    | '/admin/kewenangan-organisasi'
    | '/admin/proses-bisnis-organisasi'
    | '/sop/$id'
    | '/admin'
    | '/arsip'
    | '/login'
    | '/me'
    | '/pelaksana'
    | '/pemeriksaan'
    | '/peraturan'
    | '/persetujuan'
    | '/proses-bisnis'
    | '/sop'
    | '/tanda-tangan'
    | '/validasi/pdf'
    | '/validasi/pengesahan/$dokumenTteId/$userId'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/me'
    | '/pelaksana'
    | '/pemeriksaan'
    | '/peraturan'
    | '/persetujuan'
    | '/proses-bisnis'
    | '/sop'
    | '/tanda-tangan'
    | '/admin/akun-fti'
    | '/admin/kewenangan-organisasi'
    | '/admin/proses-bisnis-organisasi'
    | '/sop/$id'
    | '/admin/'
    | '/arsip/'
    | '/login/'
    | '/me/'
    | '/pelaksana/'
    | '/pemeriksaan/'
    | '/peraturan/'
    | '/persetujuan/'
    | '/proses-bisnis/'
    | '/sop/'
    | '/tanda-tangan/'
    | '/validasi/pdf/'
    | '/validasi/pengesahan/$dokumenTteId/$userId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  MeRoute: typeof MeRouteWithChildren
  PelaksanaRoute: typeof PelaksanaRouteWithChildren
  PemeriksaanRoute: typeof PemeriksaanRouteWithChildren
  PeraturanRoute: typeof PeraturanRouteWithChildren
  PersetujuanRoute: typeof PersetujuanRouteWithChildren
  ProsesBisnisRoute: typeof ProsesBisnisRouteWithChildren
  SopRoute: typeof SopRouteWithChildren
  TandaTanganRoute: typeof TandaTanganRouteWithChildren
  ArsipIndexRoute: typeof ArsipIndexRoute
  LoginIndexRoute: typeof LoginIndexRoute
  ValidasiPdfIndexRoute: typeof ValidasiPdfIndexRoute
  ValidasiPengesahanDokumenTteIdUserIdRoute: typeof ValidasiPengesahanDokumenTteIdUserIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tanda-tangan': {
      id: '/tanda-tangan'
      path: '/tanda-tangan'
      fullPath: '/tanda-tangan'
      preLoaderRoute: typeof TandaTanganRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sop': {
      id: '/sop'
      path: '/sop'
      fullPath: '/sop'
      preLoaderRoute: typeof SopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proses-bisnis': {
      id: '/proses-bisnis'
      path: '/proses-bisnis'
      fullPath: '/proses-bisnis'
      preLoaderRoute: typeof ProsesBisnisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/persetujuan': {
      id: '/persetujuan'
      path: '/persetujuan'
      fullPath: '/persetujuan'
      preLoaderRoute: typeof PersetujuanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/peraturan': {
      id: '/peraturan'
      path: '/peraturan'
      fullPath: '/peraturan'
      preLoaderRoute: typeof PeraturanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pemeriksaan': {
      id: '/pemeriksaan'
      path: '/pemeriksaan'
      fullPath: '/pemeriksaan'
      preLoaderRoute: typeof PemeriksaanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pelaksana': {
      id: '/pelaksana'
      path: '/pelaksana'
      fullPath: '/pelaksana'
      preLoaderRoute: typeof PelaksanaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/me': {
      id: '/me'
      path: '/me'
      fullPath: '/me'
      preLoaderRoute: typeof MeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tanda-tangan/': {
      id: '/tanda-tangan/'
      path: '/'
      fullPath: '/tanda-tangan/'
      preLoaderRoute: typeof TandaTanganIndexRouteImport
      parentRoute: typeof TandaTanganRoute
    }
    '/sop/': {
      id: '/sop/'
      path: '/'
      fullPath: '/sop/'
      preLoaderRoute: typeof SopIndexRouteImport
      parentRoute: typeof SopRoute
    }
    '/proses-bisnis/': {
      id: '/proses-bisnis/'
      path: '/'
      fullPath: '/proses-bisnis/'
      preLoaderRoute: typeof ProsesBisnisIndexRouteImport
      parentRoute: typeof ProsesBisnisRoute
    }
    '/persetujuan/': {
      id: '/persetujuan/'
      path: '/'
      fullPath: '/persetujuan/'
      preLoaderRoute: typeof PersetujuanIndexRouteImport
      parentRoute: typeof PersetujuanRoute
    }
    '/peraturan/': {
      id: '/peraturan/'
      path: '/'
      fullPath: '/peraturan/'
      preLoaderRoute: typeof PeraturanIndexRouteImport
      parentRoute: typeof PeraturanRoute
    }
    '/pemeriksaan/': {
      id: '/pemeriksaan/'
      path: '/'
      fullPath: '/pemeriksaan/'
      preLoaderRoute: typeof PemeriksaanIndexRouteImport
      parentRoute: typeof PemeriksaanRoute
    }
    '/pelaksana/': {
      id: '/pelaksana/'
      path: '/'
      fullPath: '/pelaksana/'
      preLoaderRoute: typeof PelaksanaIndexRouteImport
      parentRoute: typeof PelaksanaRoute
    }
    '/me/': {
      id: '/me/'
      path: '/'
      fullPath: '/me/'
      preLoaderRoute: typeof MeIndexRouteImport
      parentRoute: typeof MeRoute
    }
    '/login/': {
      id: '/login/'
      path: '/login'
      fullPath: '/login/'
      preLoaderRoute: typeof LoginIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/arsip/': {
      id: '/arsip/'
      path: '/arsip'
      fullPath: '/arsip/'
      preLoaderRoute: typeof ArsipIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/sop/$id': {
      id: '/sop/$id'
      path: '/$id'
      fullPath: '/sop/$id'
      preLoaderRoute: typeof SopIdRouteImport
      parentRoute: typeof SopRoute
    }
    '/admin/proses-bisnis-organisasi': {
      id: '/admin/proses-bisnis-organisasi'
      path: '/proses-bisnis-organisasi'
      fullPath: '/admin/proses-bisnis-organisasi'
      preLoaderRoute: typeof AdminProsesBisnisOrganisasiRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/kewenangan-organisasi': {
      id: '/admin/kewenangan-organisasi'
      path: '/kewenangan-organisasi'
      fullPath: '/admin/kewenangan-organisasi'
      preLoaderRoute: typeof AdminKewenanganOrganisasiRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/akun-fti': {
      id: '/admin/akun-fti'
      path: '/akun-fti'
      fullPath: '/admin/akun-fti'
      preLoaderRoute: typeof AdminAkunFtiRouteImport
      parentRoute: typeof AdminRoute
    }
    '/validasi/pdf/': {
      id: '/validasi/pdf/'
      path: '/validasi/pdf'
      fullPath: '/validasi/pdf/'
      preLoaderRoute: typeof ValidasiPdfIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/validasi/pengesahan/$dokumenTteId/$userId': {
      id: '/validasi/pengesahan/$dokumenTteId/$userId'
      path: '/validasi/pengesahan/$dokumenTteId/$userId'
      fullPath: '/validasi/pengesahan/$dokumenTteId/$userId'
      preLoaderRoute: typeof ValidasiPengesahanDokumenTteIdUserIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminAkunFtiRoute: typeof AdminAkunFtiRoute
  AdminKewenanganOrganisasiRoute: typeof AdminKewenanganOrganisasiRoute
  AdminProsesBisnisOrganisasiRoute: typeof AdminProsesBisnisOrganisasiRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAkunFtiRoute: AdminAkunFtiRoute,
  AdminKewenanganOrganisasiRoute: AdminKewenanganOrganisasiRoute,
  AdminProsesBisnisOrganisasiRoute: AdminProsesBisnisOrganisasiRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface MeRouteChildren {
  MeIndexRoute: typeof MeIndexRoute
}

const MeRouteChildren: MeRouteChildren = {
  MeIndexRoute: MeIndexRoute,
}

const MeRouteWithChildren = MeRoute._addFileChildren(MeRouteChildren)

interface PelaksanaRouteChildren {
  PelaksanaIndexRoute: typeof PelaksanaIndexRoute
}

const PelaksanaRouteChildren: PelaksanaRouteChildren = {
  PelaksanaIndexRoute: PelaksanaIndexRoute,
}

const PelaksanaRouteWithChildren = PelaksanaRoute._addFileChildren(
  PelaksanaRouteChildren,
)

interface PemeriksaanRouteChildren {
  PemeriksaanIndexRoute: typeof PemeriksaanIndexRoute
}

const PemeriksaanRouteChildren: PemeriksaanRouteChildren = {
  PemeriksaanIndexRoute: PemeriksaanIndexRoute,
}

const PemeriksaanRouteWithChildren = PemeriksaanRoute._addFileChildren(
  PemeriksaanRouteChildren,
)

interface PeraturanRouteChildren {
  PeraturanIndexRoute: typeof PeraturanIndexRoute
}

const PeraturanRouteChildren: PeraturanRouteChildren = {
  PeraturanIndexRoute: PeraturanIndexRoute,
}

const PeraturanRouteWithChildren = PeraturanRoute._addFileChildren(
  PeraturanRouteChildren,
)

interface PersetujuanRouteChildren {
  PersetujuanIndexRoute: typeof PersetujuanIndexRoute
}

const PersetujuanRouteChildren: PersetujuanRouteChildren = {
  PersetujuanIndexRoute: PersetujuanIndexRoute,
}

const PersetujuanRouteWithChildren = PersetujuanRoute._addFileChildren(
  PersetujuanRouteChildren,
)

interface ProsesBisnisRouteChildren {
  ProsesBisnisIndexRoute: typeof ProsesBisnisIndexRoute
}

const ProsesBisnisRouteChildren: ProsesBisnisRouteChildren = {
  ProsesBisnisIndexRoute: ProsesBisnisIndexRoute,
}

const ProsesBisnisRouteWithChildren = ProsesBisnisRoute._addFileChildren(
  ProsesBisnisRouteChildren,
)

interface SopRouteChildren {
  SopIdRoute: typeof SopIdRoute
  SopIndexRoute: typeof SopIndexRoute
}

const SopRouteChildren: SopRouteChildren = {
  SopIdRoute: SopIdRoute,
  SopIndexRoute: SopIndexRoute,
}

const SopRouteWithChildren = SopRoute._addFileChildren(SopRouteChildren)

interface TandaTanganRouteChildren {
  TandaTanganIndexRoute: typeof TandaTanganIndexRoute
}

const TandaTanganRouteChildren: TandaTanganRouteChildren = {
  TandaTanganIndexRoute: TandaTanganIndexRoute,
}

const TandaTanganRouteWithChildren = TandaTanganRoute._addFileChildren(
  TandaTanganRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  MeRoute: MeRouteWithChildren,
  PelaksanaRoute: PelaksanaRouteWithChildren,
  PemeriksaanRoute: PemeriksaanRouteWithChildren,
  PeraturanRoute: PeraturanRouteWithChildren,
  PersetujuanRoute: PersetujuanRouteWithChildren,
  ProsesBisnisRoute: ProsesBisnisRouteWithChildren,
  SopRoute: SopRouteWithChildren,
  TandaTanganRoute: TandaTanganRouteWithChildren,
  ArsipIndexRoute: ArsipIndexRoute,
  LoginIndexRoute: LoginIndexRoute,
  ValidasiPdfIndexRoute: ValidasiPdfIndexRoute,
  ValidasiPengesahanDokumenTteIdUserIdRoute:
    ValidasiPengesahanDokumenTteIdUserIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
