/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkRouteRouteImport } from './routes/work/route'
import { Route as PenyusunRouteRouteImport } from './routes/penyusun/route'
import { Route as ApprovalRouteRouteImport } from './routes/approval/route'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WorkIndexRouteImport } from './routes/work/index'
import { Route as PenyusunIndexRouteImport } from './routes/penyusun/index'
import { Route as LoginIndexRouteImport } from './routes/login/index'
import { Route as ArsipIndexRouteImport } from './routes/arsip/index'
import { Route as ApprovalIndexRouteImport } from './routes/approval/index'
import { Route as WorkQueueRouteImport } from './routes/work/queue'
import { Route as ValidasiPdfIndexRouteImport } from './routes/validasi/pdf/index'
import { Route as PenyusunSopIndexRouteImport } from './routes/penyusun/sop/index'
import { Route as PenyusunPeraturanIndexRouteImport } from './routes/penyusun/peraturan/index'
import { Route as PenyusunPelaksanaIndexRouteImport } from './routes/penyusun/pelaksana/index'
import { Route as PenyusunMeIndexRouteImport } from './routes/penyusun/me/index'
import { Route as AdminProcessesIndexRouteImport } from './routes/admin/processes/index'
import { Route as AdminAuthoritiesIndexRouteImport } from './routes/admin/authorities/index'
import { Route as AdminAccountsIndexRouteImport } from './routes/admin/accounts/index'
import { Route as PenyusunSopIdRouteImport } from './routes/penyusun/sop/$id'
import { Route as ValidasiPengesahanDokumenTteIdUserIdRouteImport } from './routes/validasi/pengesahan/$dokumenTteId/$userId'

const WorkRouteRoute = WorkRouteRouteImport.update({
  id: '/work',
  path: '/work',
  getParentRoute: () => rootRouteImport,
} as any)
const PenyusunRouteRoute = PenyusunRouteRouteImport.update({
  id: '/penyusun',
  path: '/penyusun',
  getParentRoute: () => rootRouteImport,
} as any)
const ApprovalRouteRoute = ApprovalRouteRouteImport.update({
  id: '/approval',
  path: '/approval',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkIndexRoute = WorkIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WorkRouteRoute,
} as any)
const PenyusunIndexRoute = PenyusunIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PenyusunRouteRoute,
} as any)
const LoginIndexRoute = LoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArsipIndexRoute = ArsipIndexRouteImport.update({
  id: '/arsip/',
  path: '/arsip/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApprovalIndexRoute = ApprovalIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ApprovalRouteRoute,
} as any)
const WorkQueueRoute = WorkQueueRouteImport.update({
  id: '/queue',
  path: '/queue',
  getParentRoute: () => WorkRouteRoute,
} as any)
const ValidasiPdfIndexRoute = ValidasiPdfIndexRouteImport.update({
  id: '/validasi/pdf/',
  path: '/validasi/pdf/',
  getParentRoute: () => rootRouteImport,
} as any)
const PenyusunSopIndexRoute = PenyusunSopIndexRouteImport.update({
  id: '/sop/',
  path: '/sop/',
  getParentRoute: () => PenyusunRouteRoute,
} as any)
const PenyusunPeraturanIndexRoute = PenyusunPeraturanIndexRouteImport.update({
  id: '/peraturan/',
  path: '/peraturan/',
  getParentRoute: () => PenyusunRouteRoute,
} as any)
const PenyusunPelaksanaIndexRoute = PenyusunPelaksanaIndexRouteImport.update({
  id: '/pelaksana/',
  path: '/pelaksana/',
  getParentRoute: () => PenyusunRouteRoute,
} as any)
const PenyusunMeIndexRoute = PenyusunMeIndexRouteImport.update({
  id: '/me/',
  path: '/me/',
  getParentRoute: () => PenyusunRouteRoute,
} as any)
const AdminProcessesIndexRoute = AdminProcessesIndexRouteImport.update({
  id: '/processes/',
  path: '/processes/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminAuthoritiesIndexRoute = AdminAuthoritiesIndexRouteImport.update({
  id: '/authorities/',
  path: '/authorities/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminAccountsIndexRoute = AdminAccountsIndexRouteImport.update({
  id: '/accounts/',
  path: '/accounts/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const PenyusunSopIdRoute = PenyusunSopIdRouteImport.update({
  id: '/sop/$id',
  path: '/sop/$id',
  getParentRoute: () => PenyusunRouteRoute,
} as any)
const ValidasiPengesahanDokumenTteIdUserIdRoute =
  ValidasiPengesahanDokumenTteIdUserIdRouteImport.update({
    id: '/validasi/pengesahan/$dokumenTteId/$userId',
    path: '/validasi/pengesahan/$dokumenTteId/$userId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/approval': typeof ApprovalRouteRouteWithChildren
  '/penyusun': typeof PenyusunRouteRouteWithChildren
  '/work': typeof WorkRouteRouteWithChildren
  '/work/queue': typeof WorkQueueRoute
  '/approval/': typeof ApprovalIndexRoute
  '/arsip/': typeof ArsipIndexRoute
  '/login/': typeof LoginIndexRoute
  '/penyusun/': typeof PenyusunIndexRoute
  '/work/': typeof WorkIndexRoute
  '/penyusun/sop/$id': typeof PenyusunSopIdRoute
  '/admin/accounts/': typeof AdminAccountsIndexRoute
  '/admin/authorities/': typeof AdminAuthoritiesIndexRoute
  '/admin/processes/': typeof AdminProcessesIndexRoute
  '/penyusun/me/': typeof PenyusunMeIndexRoute
  '/penyusun/pelaksana/': typeof PenyusunPelaksanaIndexRoute
  '/penyusun/peraturan/': typeof PenyusunPeraturanIndexRoute
  '/penyusun/sop/': typeof PenyusunSopIndexRoute
  '/validasi/pdf/': typeof ValidasiPdfIndexRoute
  '/validasi/pengesahan/$dokumenTteId/$userId': typeof ValidasiPengesahanDokumenTteIdUserIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/work/queue': typeof WorkQueueRoute
  '/approval': typeof ApprovalIndexRoute
  '/arsip': typeof ArsipIndexRoute
  '/login': typeof LoginIndexRoute
  '/penyusun': typeof PenyusunIndexRoute
  '/work': typeof WorkIndexRoute
  '/penyusun/sop/$id': typeof PenyusunSopIdRoute
  '/admin/accounts': typeof AdminAccountsIndexRoute
  '/admin/authorities': typeof AdminAuthoritiesIndexRoute
  '/admin/processes': typeof AdminProcessesIndexRoute
  '/penyusun/me': typeof PenyusunMeIndexRoute
  '/penyusun/pelaksana': typeof PenyusunPelaksanaIndexRoute
  '/penyusun/peraturan': typeof PenyusunPeraturanIndexRoute
  '/penyusun/sop': typeof PenyusunSopIndexRoute
  '/validasi/pdf': typeof ValidasiPdfIndexRoute
  '/validasi/pengesahan/$dokumenTteId/$userId': typeof ValidasiPengesahanDokumenTteIdUserIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/approval': typeof ApprovalRouteRouteWithChildren
  '/penyusun': typeof PenyusunRouteRouteWithChildren
  '/work': typeof WorkRouteRouteWithChildren
  '/work/queue': typeof WorkQueueRoute
  '/approval/': typeof ApprovalIndexRoute
  '/arsip/': typeof ArsipIndexRoute
  '/login/': typeof LoginIndexRoute
  '/penyusun/': typeof PenyusunIndexRoute
  '/work/': typeof WorkIndexRoute
  '/penyusun/sop/$id': typeof PenyusunSopIdRoute
  '/admin/accounts/': typeof AdminAccountsIndexRoute
  '/admin/authorities/': typeof AdminAuthoritiesIndexRoute
  '/admin/processes/': typeof AdminProcessesIndexRoute
  '/penyusun/me/': typeof PenyusunMeIndexRoute
  '/penyusun/pelaksana/': typeof PenyusunPelaksanaIndexRoute
  '/penyusun/peraturan/': typeof PenyusunPeraturanIndexRoute
  '/penyusun/sop/': typeof PenyusunSopIndexRoute
  '/validasi/pdf/': typeof ValidasiPdfIndexRoute
  '/validasi/pengesahan/$dokumenTteId/$userId': typeof ValidasiPengesahanDokumenTteIdUserIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/approval'
    | '/penyusun'
    | '/work'
    | '/work/queue'
    | '/approval/'
    | '/arsip/'
    | '/login/'
    | '/penyusun/'
    | '/work/'
    | '/penyusun/sop/$id'
    | '/admin/accounts/'
    | '/admin/authorities/'
    | '/admin/processes/'
    | '/penyusun/me/'
    | '/penyusun/pelaksana/'
    | '/penyusun/peraturan/'
    | '/penyusun/sop/'
    | '/validasi/pdf/'
    | '/validasi/pengesahan/$dokumenTteId/$userId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/work/queue'
    | '/approval'
    | '/arsip'
    | '/login'
    | '/penyusun'
    | '/work'
    | '/penyusun/sop/$id'
    | '/admin/accounts'
    | '/admin/authorities'
    | '/admin/processes'
    | '/penyusun/me'
    | '/penyusun/pelaksana'
    | '/penyusun/peraturan'
    | '/penyusun/sop'
    | '/validasi/pdf'
    | '/validasi/pengesahan/$dokumenTteId/$userId'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/approval'
    | '/penyusun'
    | '/work'
    | '/work/queue'
    | '/approval/'
    | '/arsip/'
    | '/login/'
    | '/penyusun/'
    | '/work/'
    | '/penyusun/sop/$id'
    | '/admin/accounts/'
    | '/admin/authorities/'
    | '/admin/processes/'
    | '/penyusun/me/'
    | '/penyusun/pelaksana/'
    | '/penyusun/peraturan/'
    | '/penyusun/sop/'
    | '/validasi/pdf/'
    | '/validasi/pengesahan/$dokumenTteId/$userId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  ApprovalRouteRoute: typeof ApprovalRouteRouteWithChildren
  PenyusunRouteRoute: typeof PenyusunRouteRouteWithChildren
  WorkRouteRoute: typeof WorkRouteRouteWithChildren
  ArsipIndexRoute: typeof ArsipIndexRoute
  LoginIndexRoute: typeof LoginIndexRoute
  ValidasiPdfIndexRoute: typeof ValidasiPdfIndexRoute
  ValidasiPengesahanDokumenTteIdUserIdRoute: typeof ValidasiPengesahanDokumenTteIdUserIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/work': {
      id: '/work'
      path: '/work'
      fullPath: '/work'
      preLoaderRoute: typeof WorkRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/penyusun': {
      id: '/penyusun'
      path: '/penyusun'
      fullPath: '/penyusun'
      preLoaderRoute: typeof PenyusunRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/approval': {
      id: '/approval'
      path: '/approval'
      fullPath: '/approval'
      preLoaderRoute: typeof ApprovalRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/work/': {
      id: '/work/'
      path: '/'
      fullPath: '/work/'
      preLoaderRoute: typeof WorkIndexRouteImport
      parentRoute: typeof WorkRouteRoute
    }
    '/penyusun/': {
      id: '/penyusun/'
      path: '/'
      fullPath: '/penyusun/'
      preLoaderRoute: typeof PenyusunIndexRouteImport
      parentRoute: typeof PenyusunRouteRoute
    }
    '/login/': {
      id: '/login/'
      path: '/login'
      fullPath: '/login/'
      preLoaderRoute: typeof LoginIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/arsip/': {
      id: '/arsip/'
      path: '/arsip'
      fullPath: '/arsip/'
      preLoaderRoute: typeof ArsipIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/approval/': {
      id: '/approval/'
      path: '/'
      fullPath: '/approval/'
      preLoaderRoute: typeof ApprovalIndexRouteImport
      parentRoute: typeof ApprovalRouteRoute
    }
    '/work/queue': {
      id: '/work/queue'
      path: '/queue'
      fullPath: '/work/queue'
      preLoaderRoute: typeof WorkQueueRouteImport
      parentRoute: typeof WorkRouteRoute
    }
    '/validasi/pdf/': {
      id: '/validasi/pdf/'
      path: '/validasi/pdf'
      fullPath: '/validasi/pdf/'
      preLoaderRoute: typeof ValidasiPdfIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/penyusun/sop/': {
      id: '/penyusun/sop/'
      path: '/sop'
      fullPath: '/penyusun/sop/'
      preLoaderRoute: typeof PenyusunSopIndexRouteImport
      parentRoute: typeof PenyusunRouteRoute
    }
    '/penyusun/peraturan/': {
      id: '/penyusun/peraturan/'
      path: '/peraturan'
      fullPath: '/penyusun/peraturan/'
      preLoaderRoute: typeof PenyusunPeraturanIndexRouteImport
      parentRoute: typeof PenyusunRouteRoute
    }
    '/penyusun/pelaksana/': {
      id: '/penyusun/pelaksana/'
      path: '/pelaksana'
      fullPath: '/penyusun/pelaksana/'
      preLoaderRoute: typeof PenyusunPelaksanaIndexRouteImport
      parentRoute: typeof PenyusunRouteRoute
    }
    '/penyusun/me/': {
      id: '/penyusun/me/'
      path: '/me'
      fullPath: '/penyusun/me/'
      preLoaderRoute: typeof PenyusunMeIndexRouteImport
      parentRoute: typeof PenyusunRouteRoute
    }
    '/admin/processes/': {
      id: '/admin/processes/'
      path: '/processes'
      fullPath: '/admin/processes/'
      preLoaderRoute: typeof AdminProcessesIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/authorities/': {
      id: '/admin/authorities/'
      path: '/authorities'
      fullPath: '/admin/authorities/'
      preLoaderRoute: typeof AdminAuthoritiesIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/accounts/': {
      id: '/admin/accounts/'
      path: '/accounts'
      fullPath: '/admin/accounts/'
      preLoaderRoute: typeof AdminAccountsIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/penyusun/sop/$id': {
      id: '/penyusun/sop/$id'
      path: '/sop/$id'
      fullPath: '/penyusun/sop/$id'
      preLoaderRoute: typeof PenyusunSopIdRouteImport
      parentRoute: typeof PenyusunRouteRoute
    }
    '/validasi/pengesahan/$dokumenTteId/$userId': {
      id: '/validasi/pengesahan/$dokumenTteId/$userId'
      path: '/validasi/pengesahan/$dokumenTteId/$userId'
      fullPath: '/validasi/pengesahan/$dokumenTteId/$userId'
      preLoaderRoute: typeof ValidasiPengesahanDokumenTteIdUserIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteRouteChildren {
  AdminAccountsIndexRoute: typeof AdminAccountsIndexRoute
  AdminAuthoritiesIndexRoute: typeof AdminAuthoritiesIndexRoute
  AdminProcessesIndexRoute: typeof AdminProcessesIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminAccountsIndexRoute: AdminAccountsIndexRoute,
  AdminAuthoritiesIndexRoute: AdminAuthoritiesIndexRoute,
  AdminProcessesIndexRoute: AdminProcessesIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

interface ApprovalRouteRouteChildren {
  ApprovalIndexRoute: typeof ApprovalIndexRoute
}

const ApprovalRouteRouteChildren: ApprovalRouteRouteChildren = {
  ApprovalIndexRoute: ApprovalIndexRoute,
}

const ApprovalRouteRouteWithChildren = ApprovalRouteRoute._addFileChildren(
  ApprovalRouteRouteChildren,
)

interface PenyusunRouteRouteChildren {
  PenyusunIndexRoute: typeof PenyusunIndexRoute
  PenyusunSopIdRoute: typeof PenyusunSopIdRoute
  PenyusunMeIndexRoute: typeof PenyusunMeIndexRoute
  PenyusunPelaksanaIndexRoute: typeof PenyusunPelaksanaIndexRoute
  PenyusunPeraturanIndexRoute: typeof PenyusunPeraturanIndexRoute
  PenyusunSopIndexRoute: typeof PenyusunSopIndexRoute
}

const PenyusunRouteRouteChildren: PenyusunRouteRouteChildren = {
  PenyusunIndexRoute: PenyusunIndexRoute,
  PenyusunSopIdRoute: PenyusunSopIdRoute,
  PenyusunMeIndexRoute: PenyusunMeIndexRoute,
  PenyusunPelaksanaIndexRoute: PenyusunPelaksanaIndexRoute,
  PenyusunPeraturanIndexRoute: PenyusunPeraturanIndexRoute,
  PenyusunSopIndexRoute: PenyusunSopIndexRoute,
}

const PenyusunRouteRouteWithChildren = PenyusunRouteRoute._addFileChildren(
  PenyusunRouteRouteChildren,
)

interface WorkRouteRouteChildren {
  WorkQueueRoute: typeof WorkQueueRoute
  WorkIndexRoute: typeof WorkIndexRoute
}

const WorkRouteRouteChildren: WorkRouteRouteChildren = {
  WorkQueueRoute: WorkQueueRoute,
  WorkIndexRoute: WorkIndexRoute,
}

const WorkRouteRouteWithChildren = WorkRouteRoute._addFileChildren(
  WorkRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  ApprovalRouteRoute: ApprovalRouteRouteWithChildren,
  PenyusunRouteRoute: PenyusunRouteRouteWithChildren,
  WorkRouteRoute: WorkRouteRouteWithChildren,
  ArsipIndexRoute: ArsipIndexRoute,
  LoginIndexRoute: LoginIndexRoute,
  ValidasiPdfIndexRoute: ValidasiPdfIndexRoute,
  ValidasiPengesahanDokumenTteIdUserIdRoute:
    ValidasiPengesahanDokumenTteIdUserIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
