import type {
  PengajuanEvaluasi,
  PengajuanEvaluasiShell,
  HasilEvaluasiDisplay,
} from '@/types/dto/evaluasi.dto'
import { buildNilaiEvaluasiClientId } from '@/types/dto/evaluasi.dto'

export function mapEvaluasiShellToPengajuan(
  shell: PengajuanEvaluasiShell,
): PengajuanEvaluasi {
  return {
    id: shell.id,
    opdId: shell.opdId,
    opdNama: shell.opdNama,
    jenis: shell.jenis as PengajuanEvaluasi['jenis'],
    status: shell.status as PengajuanEvaluasi['status'],
    statusLabel: shell.statusLabel,
    nomorBA: shell.nomorBA,
    tanggalPermintaan: shell.tanggalPermintaan,
    tanggalEvaluasi: shell.tanggalEvaluasi,
    tanggalVerifikasi: shell.tanggalVerifikasi ?? null,
    nilaiOPD: shell.nilaiOPD,
    diverifikasiOlehUserId: shell.diverifikasiOlehUserId,
    namaPjEvaluator: shell.namaPjEvaluator,
    ditandatanganiOlehPjPenyusunUserId: shell.ditandatanganiOlehPjPenyusunUserId,
    namaPjPenyusun: shell.namaPjPenyusun,
    tanggalTTDBaPjPenyusun: shell.tanggalTTDBaPjPenyusun,
    diselesaikanOlehId: shell.diselesaikanOlehId,
    diselesaikanOleh: shell.diselesaikanOleh,
    opd: shell.opd,
    timEvaluasi: shell.timEvaluasi,
    tanggalDiselesaikan: shell.tanggalDiselesaikan,
    alasanPenolakan: shell.alasanPenolakan,
    tanggalDitolak: shell.tanggalDitolak,
    ditolakOlehId: shell.ditolakOlehId,
    ditolakOleh: shell.ditolakOleh,
    nilaiEvaluasi: shell.nilaiEvaluasi,
    sopList: shell.sopItems.map((item) => ({
      id: buildNilaiEvaluasiClientId(shell.id, item.detailSopId),
      sopDetailId: item.detailSopId,
      judul: item.judul,
      nomor: item.nomorSOP,
      nama: item.judul,
      nomorSOP: item.nomorSOP,
      status: item.statusDetailSop,
      statusLabel: item.statusDetailSopLabel,
      hasil: item.hasilEvaluasi as HasilEvaluasiDisplay,
      hasilLabel: item.hasilEvaluasiLabel,
    })),
    riwayatEvaluasi: shell.timelineNilai.map((item) => ({
      id: item.id,
      sopDetailId: item.sopDetailId,
      evaluatorId: item.evaluatorId,
      evaluatorNama: item.evaluatorNama,
      hasilSebelum: item.hasilSebelum,
      hasilSesudah: item.hasilSesudah,
      catatanSebelum: item.catatanSebelum,
      catatanSesudah: item.catatanSesudah,
      createdAt: item.createdAt,
    })),
    version: shell.version,
    createdAt: shell.createdAt,
    updatedAt: shell.updatedAt,
  }
}
