-- Rename StatusSOP enum values:
-- SIAP_DIEVALUASI   -> MENUNGGU_PENGAJUAN_EVALUASI
-- SIAP_DIVERIFIKASI -> MENUNGGU_TTD_PJ_EVALUATOR
--
-- Expand first so existing rows can be rewritten before the old enum values are removed.

ALTER TABLE `DetailSOP`
  MODIFY `status` ENUM(
    'DRAFT',
    'SEDANG_DISUSUN',
    'SIAP_DIEVALUASI',
    'MENUNGGU_PENGAJUAN_EVALUASI',
    'DIAJUKAN_EVALUASI',
    'SEDANG_DIEVALUASI',
    'REVISI_DARI_EVALUATOR',
    'SIAP_DIVERIFIKASI',
    'MENUNGGU_TTD_PJ_EVALUATOR',
    'DIVERIFIKASI_PJ_EVALUATOR_ORGANISASI',
    'BERLAKU',
    'DIGANTIKAN',
    'DICABUT'
  ) NOT NULL DEFAULT 'DRAFT';

UPDATE `DetailSOP`
SET `status` = 'MENUNGGU_PENGAJUAN_EVALUASI'
WHERE `status` = 'SIAP_DIEVALUASI';

UPDATE `DetailSOP`
SET `status` = 'MENUNGGU_TTD_PJ_EVALUATOR'
WHERE `status` = 'SIAP_DIVERIFIKASI';

ALTER TABLE `DetailSOP`
  MODIFY `status` ENUM(
    'DRAFT',
    'SEDANG_DISUSUN',
    'MENUNGGU_PENGAJUAN_EVALUASI',
    'DIAJUKAN_EVALUASI',
    'SEDANG_DIEVALUASI',
    'REVISI_DARI_EVALUATOR',
    'MENUNGGU_TTD_PJ_EVALUATOR',
    'DIVERIFIKASI_PJ_EVALUATOR_ORGANISASI',
    'BERLAKU',
    'DIGANTIKAN',
    'DICABUT'
  ) NOT NULL DEFAULT 'DRAFT';
