// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import 'dotenv/config';
import { defineConfig } from 'prisma/config';

function requiredEnvironment(name: string): string {
  const value = process.env[name]?.trim();
  if (value === undefined || value === '') {
    throw new Error(`${name} wajib diisi`);
  }
  return value;
}

function environmentOrDefault(name: string, fallback: string): string {
  const value = process.env[name]?.trim();
  return value === undefined || value === '' ? fallback : value;
}

function resolveDatabaseUrl(): string {
  if (process.env['DATABASE_URL']) {
    return process.env['DATABASE_URL'];
  }

  const port = Number(environmentOrDefault('DATABASE_PORT', '3306'));
  if (!Number.isInteger(port) || port < 1 || port > 65535) {
    throw new Error('DATABASE_PORT tidak valid');
  }

  const url = new URL('mysql://localhost');
  url.hostname = environmentOrDefault('DATABASE_HOST', 'localhost');
  url.port = String(port);
  url.username = environmentOrDefault('DATABASE_USER', 'sop_app');
  url.password = requiredEnvironment('DATABASE_PASSWORD');
  url.pathname = `/${environmentOrDefault('DATABASE_NAME', 'sop_fti')}`;
  return url.toString();
}

export default defineConfig({
  // Prisma 7 supports schema folders; schema.prisma remains the main file and
  // domain additions can live under prisma/models/*.prisma.
  schema: 'prisma',
  migrations: {
    path: 'prisma/migrations',
    seed: 'ts-node --compiler-options {"module":"CommonJS"} prisma/seed.ts',
  },
  datasource: {
    url: resolveDatabaseUrl(),
  },
});
