-- Rename StatusPengajuanEvaluasi.DIVERIFIKASI_PJ_EVALUATOR to DITANDATANGANI_PJ_EVALUATOR.
-- Expand first so existing rows can be rewritten before the old enum value is removed.

ALTER TABLE `PengajuanEvaluasi`
  MODIFY `status` ENUM(
    'SEDANG_DIEVALUASI',
    'SELESAI_DIEVALUASI',
    'DIVERIFIKASI_PJ_EVALUATOR',
    'DITANDATANGANI_PJ_EVALUATOR',
    'DITANDATANGANI_PJ_PENYUSUN',
    'SELESAI'
  ) NOT NULL DEFAULT 'SEDANG_DIEVALUASI';

UPDATE `PengajuanEvaluasi`
SET `status` = 'DITANDATANGANI_PJ_EVALUATOR'
WHERE `status` = 'DIVERIFIKASI_PJ_EVALUATOR';

ALTER TABLE `PengajuanEvaluasi`
  MODIFY `status` ENUM(
    'SEDANG_DIEVALUASI',
    'SELESAI_DIEVALUASI',
    'DITANDATANGANI_PJ_EVALUATOR',
    'DITANDATANGANI_PJ_PENYUSUN',
    'SELESAI'
  ) NOT NULL DEFAULT 'SEDANG_DIEVALUASI';
