ALTER TABLE `PengajuanEvaluasi`
  MODIFY `status` ENUM(
    'SEDANG_DIEVALUASI',
    'DITOLAK',
    'SELESAI_DIEVALUASI',
    'DITANDATANGANI_PJ_EVALUATOR',
    'DITANDATANGANI_PJ_PENYUSUN',
    'SELESAI'
  ) NOT NULL DEFAULT 'SEDANG_DIEVALUASI',
  ADD COLUMN `alasanPenolakan` TEXT NULL,
  ADD COLUMN `ditolakOlehId` CHAR(36) NULL,
  ADD COLUMN `tanggalDitolak` DATETIME(3) NULL;

ALTER TABLE `DetailSOP`
  MODIFY `status` ENUM(
    'DRAFT',
    'SEDANG_DISUSUN',
    'MENUNGGU_PENGAJUAN_EVALUASI',
    'DIAJUKAN_EVALUASI',
    'SEDANG_DIEVALUASI',
    'REVISI_DARI_EVALUATOR',
    'DITOLAK_EVALUATOR',
    'MENUNGGU_TTD_PJ_EVALUATOR',
    'DIVERIFIKASI_PJ_EVALUATOR_ORGANISASI',
    'BERLAKU',
    'DIGANTIKAN',
    'DICABUT'
  ) NOT NULL DEFAULT 'DRAFT';

ALTER TABLE `NilaiEvaluasi`
  MODIFY `hasil` ENUM('SESUAI', 'PERLU_PERBAIKAN', 'DITOLAK') NULL;

ALTER TABLE `LogNilaiEvaluasi`
  MODIFY `hasilSebelum` ENUM('SESUAI', 'PERLU_PERBAIKAN', 'DITOLAK') NULL,
  MODIFY `hasilSesudah` ENUM('SESUAI', 'PERLU_PERBAIKAN', 'DITOLAK') NULL;

CREATE INDEX `PengajuanEvaluasi_ditolakOlehId_idx`
  ON `PengajuanEvaluasi`(`ditolakOlehId`);

ALTER TABLE `PengajuanEvaluasi`
  ADD CONSTRAINT `PengajuanEvaluasi_ditolakOlehId_fkey`
  FOREIGN KEY (`ditolakOlehId`) REFERENCES `Pengguna`(`penggunaId`)
  ON DELETE RESTRICT ON UPDATE CASCADE;
