-- TTE values are composed/generated by application code and must fit their valid contracts.
-- SOP number: 500-char base + '-' + 255-char SOP number = 756.
-- SOP title: 2000-char base + ' - ' + 500-char SOP title = 2503.
ALTER TABLE `DokumenTte`
  MODIFY `nomorDokumen` VARCHAR(756) NOT NULL,
  MODIFY `judulDokumen` VARCHAR(2503) NOT NULL;

-- Signing metadata written by the PDF signer:
-- PKCS7_DETACHED = 14 chars; X.509 serial may be 20 octets / 40 hex chars;
-- issuer/subject are complete distinguished names and are not sample-sized strings.
ALTER TABLE `RiwayatTandaTangan`
  MODIFY `signatureFormat` VARCHAR(14) NULL,
  MODIFY `certSerialNumber` VARCHAR(40) NULL,
  MODIFY `certIssuer` TEXT NULL,
  MODIFY `certSubject` TEXT NULL;
